### ISSUE TITLE
 Failed to fetch plugin

### ISSUE THREAD

**Issue by fgagneten** [shprink/ionic-native-transitions#144]
I want to install the plugin with

    cordova plugin add https://github.com/shprink/ionic-native-transitions#1.0.3

But I get:

    git rev-list -n1 1.0.3: fatal: ambiguous argument '1.0.3': unknown revision or path not in the working tree.
    git rev-list -n1 1.0.3: Use '--' to separate paths from revisions, like this:
    ...

I can only install with cordova version 0.6.5, but I need the changes of the lastest commit, I mean version 1.0.3.

I can install with bower version 1.0.3 but the console of real device get the following message:

    [native transition] The plugin is either disabled or nativepagetransitions plugin by telerik is not present. If you are getting this message in a browser, this is normal behavior, native transitions only work on device." I was debugging with Moto X 5 Plus.

So:
if I install the plugin with bower -> i get the message above

If I install the plugin with cordova -> only I can install version 0.6.5

Someone can help me ASAP

**Comment by darshanrampatel** [comment]
@fgagneten Try this: `cordova plugin add https://github.com/shprink/ionic-native-transitions#v1.0.3`

**Comment by fgagneten** [comment]
Ok @darshanrampatel I will try this afternoon. Did you install version 1.0.3 with cordova successfully? Thanks.

**Comment by fgagneten** [comment]
@darshanrampatel , I got the following error after running the code that you tell me: cordova plugin add https://github.com/shprink/ionic-native-transitions#v1.0.3
    

> Error: Failed to fetch plugin https://github.com/shprink/ionic-native-transitions#v1.0.3 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

Version:

**Ionic -v**

    [WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.
    3.19.0-alpha.195e089e

**node -v**

    v6.10.1

*npm -v*

    3.10.8

Let me know if you need another infomation.

**Comment by johnnynode** [comment]
Same Here:
```
$ cordova plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.6.5
Error: Failed to fetch plugin https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.6.5 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
TypeError: Parameter "url" must be a string, not undefined
```

and

```
$ cordova plugin add https://github.com/shprink/ionic-native-transitions#v1.0.3
Error: Failed to fetch plugin https://github.com/shprink/ionic-native-transitions#v1.0.3 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
TypeError: Parameter "url" must be a string, not undefined
```

Fixed by below:

- https://stackoverflow.com/questions/43856285/failed-to-get-absolute-path-to-installed-module

cordova version 7 is not stable.
```
$ cordova -v
7.1.0

$ sudo npm i -g cordova@6.5.0

$ cordova -v
6.5.0

$ cordova plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.6.5
Fetching plugin "https://github.com/Telerik-Verified-Plugins/NativePageTransitions" via git clone
Repository "https://github.com/Telerik-Verified-Plugins/NativePageTransitions" checked out to git ref "0.6.5".
Installing "com.telerik.plugins.nativepagetransitions" for android
ANDROID_HOME=/Users/Johnny/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
Subproject Path: CordovaLib

> Configure project :
Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead
.
        at build_gbu6pfq6xj89i8y3b1w77z6m.run(/Users/Johnny/code/work/app/dds-mobile-app/platforms/android/build.gradle:143)

> Configure project :CordovaLib
publishNonDefault is deprecated and has no effect anymore. All variants are now published.


BUILD SUCCESSFUL in 2s
2 actionable tasks: 1 executed, 1 up-to-date

```

**Comment by darshanrampatel** [comment]
Sorry, I was confused before. The `ionic-native-transitions` is not a cordova plugin so needs to be added via *npm* or *bower*.

I can add the NativePageTransitions cordova plugin fine:
```
PS C:\testapp> cordova plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.6.5
Adding com.telerik.plugins.nativepagetransitions to package.json
Saved plugin info for "com.telerik.plugins.nativepagetransitions" to config.xml
```

**Comment by fgagneten** [comment]
Yes I can install page transition version 0.6.5, but there is some bugs that was solved after that version, that's the reason I need version 1.0.3. For example,I get error like this one that was solved but I don't think that was solved on version 0.6.5 https://github.com/shprink/ionic-native-transitions/pull/137

**Comment by fgagneten** [comment]
@darshanrampatel . I know whats going on. **ionic-native-transitions** is not the same as NativePageTransitions. NativePageTransitions the lastes version was 0.6.5.

What I don't know why there are two libraries with similar name. For my cordova ionic app **ionic-native-transitions** not working.


Is there a possibility to use **ionic-native-transitions** instead of **NativePageTransitions** in my cordova app?
